### ISSUE TITLE
minecraft-data makes programs (Sveltekit) crash

### ISSUE THREAD

**Issue by lolouthefox** [PrismarineJS/node-minecraft-data#349]
I have an issue where using `node-minecraft-data` makes my code crash, there's is probably too much data to load. Is there any way to fix it, or is it a problem with the package?

**Comment by extremeheat** [comment]
You need to elaborate on what the actual problem is beyond "it crashes". As this is an issue on your side I can't say what the problem is but from what it sounds if your bundle is too big then you may need to add logic to only include files that are relevant to your project in the bundle.

If you are using webpack you can take a look at https://webpack.js.org/plugins/ignore-plugin/

**Comment by lolouthefox** [comment]
I said, I'm using Sveltekit and there is literally no way to control that. The package is just importing everything when it loads and it crashes the Node server and the client (web browser).

**Comment by rom1504** [comment]
use a framework that provides better features than "literally no way to control that" then.

**Comment by rom1504** [comment]
or you can give us some information on what you are doing; your call

**Comment by lolouthefox** [comment]
I said! I'm just importing the lib, nothing else. I literally use import whatever from 'node-minecraft-data'; on client ("+page.svelte") in a script tag.

**Comment by lolouthefox** [comment]
The package/lib is not optimized, that's it. Y'all should use functions to import data dynamically instead of reading all files and storing everything in RAM

**Comment by lolouthefox** [comment]
At least just assign the issue to me so I work on it some time later and make the lib load correctly
